// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"NecroBetterText","status":true,"description":"Adds more text features! <pluginID Necro Better Text>","parameters":{"Wrap On":"true","Alignment":"left"}}
];
